apiVersion: apps/v1
kind: Deployment
metadata:
  name: refinery
  labels:
    app: refinery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refinery
  template:
    metadata:
      labels:
        app: refinery
    spec:
      containers:
      - name: refinery
        image: deseretdigital/nostromo:chain
        ports:
        - containerPort: 9800
---
apiVersion: v1
kind: Service
metadata:
  name: refinery-service
spec:
  type: LoadBalancer
  selector:
    app: refinery
  ports:
    - name: refinery
      protocol: TCP
      port: 9800
      targetPort: 9800 # Unnecessary because it's defaulted to port
